name: OffhandTorchLight
main: com.stdnullptr.OffhandTorchLight
version: 1.0.0
api-version: 1.19
description: The plugin makes the torch emit light when held in offhand
commands:
  torchlight:
    description: Enables or disables offhand torch lighting.
    usage: /torchlight <on | off>
permissions:
  torchlight.toggle:
    description: Allows toggling the offhand torch lighting feature.
    default: op